[workspace]
members = [
  "eckd",
  "recetcd",
  "ecetcd",
  "etcd-proto",
  "bencher",
  "kubernetes-proto",
  "experiments/bencher",
  "experiments/kubernetes-scheduling",
  "experiments/etcd-bencher",
]

[profile.release]
debug = true
