[workspace]
members = [
  "eckd",
  "recetcd",
  "ecetcd",
  "etcd-proto",
  "bencher",
  "kubernetes-proto",
  "experiments/bencher",
  "experiments/kubernetes-scheduling",
  "experiments/etcd-bencher",
]

[profile.release]
debug = true

[patch."https://github.com/automerge/automerge-rs"]
automerge = { git = "https://github.com/automerge//automerge-rs", branch = "value-proxy" }
automerge-protocol = { git = "https://github.com/automerge//automerge-rs", branch = "value-proxy" }
automerge-backend = { git = "https://github.com/automerge//automerge-rs", branch = "value-proxy" }
automerge-frontend = { git = "https://github.com/automerge//automerge-rs", branch = "value-proxy" }
