[workspace]
members = [
  "eckd",
  "recetcd",
  "ecetcd",
  "etcd-proto",
  "peer-proto",
  "bencher",
  "kubernetes-proto",
  "experiments/bencher",
  "experiments/kubernetes-scheduling",
  "experiments/etcd-bencher",
]

[profile.release]
debug = true

# [patch."https://github.com/automerge/automerge-rs"]
# automerge = { git = "https://github.com//jeffa5/automerge-rs", branch = "state-tree-and-sync-improvements" }
# automerge-protocol = { git = "https://github.com//jeffa5/automerge-rs", branch = "state-tree-and-sync-improvements" }
# automerge-backend = { git = "https://github.com//jeffa5/automerge-rs", branch = "state-tree-and-sync-improvements" }
# automerge-frontend = { git = "https://github.com//jeffa5/automerge-rs", branch = "state-tree-and-sync-improvements" }

[patch."https://github.com/automerge/automerge-rs"]
automerge = { git = "https://github.com//automerge/automerge-rs", branch = "frontend-sorted-map" }
automerge-protocol = { git = "https://github.com//automerge/automerge-rs", branch = "frontend-sorted-map" }
automerge-backend = { git = "https://github.com//automerge/automerge-rs", branch = "frontend-sorted-map" }
automerge-frontend = { git = "https://github.com//automerge/automerge-rs", branch = "frontend-sorted-map" }

[patch."https://github.com/jeffa5/automergeable"]
automergeable = { git = "https://github.com//jeffa5/automergeable", branch = "sorted-map" }
