[workspace]
members = [
  "crates/*",
  "experiments/bencher",
  # "experiments/kubernetes-scheduling",
  # "experiments/etcd-bencher",
]

[profile.release]
debug = true

# [patch."https://github.com/automerge/automerge-rs"]
# PR: https://github.com/automerge/automerge-rs/pull/362
# automerge = { git = "https://github.com/jeffa5/automerge-rs", branch = "opt-seek-op" }
