[workspace]
members = [
  "eckd",
  "recetcd",
  "ecetcd",
  "etcd-proto",
  "peer-proto",
  "bencher",
  "kubernetes-proto",
  "experiments/bencher",
  "experiments/kubernetes-scheduling",
  "experiments/etcd-bencher",
]

[profile.release]
debug = true

[patch."https://github.com/automerge/automerge-rs"]
automerge = { git = "https://github.com//jeffa5/automerge-rs", branch = "dev" }
automerge-protocol = { git = "https://github.com//jeffa5/automerge-rs", branch = "dev" }
automerge-backend = { git = "https://github.com//jeffa5/automerge-rs", branch = "dev" }
automerge-frontend = { git = "https://github.com//jeffa5/automerge-rs", branch = "dev" }

[patch."https://github.com/jeffa5/automergeable"]
automergeable = { git = "https://github.com//jeffa5/automergeable", branch = "sorted-map" }
