[workspace]
members = [
  "crates/*",
  "experiments/bencher",
  "experiments/kubernetes-scheduling",
  "experiments/etcd-bencher",
  "experiments/go-ycsb",
  "experiments/bencher",
]

[profile.release]
debug = true
