[package]
name = "eckd"
version = "0.1.0"
authors = ["Andrew Jeffery <dev@jeffas.io>"]
edition = "2018"

[dependencies]
sled = "0.34.6"
tonic = { version = "0.4.0", features = ["transport", "tls"] }
prost = "0.7"
tokio = { version = "1.1.0", features = ["macros", "rt", "rt-multi-thread", "fs"] }
etcd-proto = { path = "../etcd-proto" }
derive_builder = "0.9.0"
structopt = "0.3.21"
url = "2.2.0"
thiserror = "1.0.23"
futures = "0.3.12"
serde = { version = "1.0.123", features = ["derive"] }
bincode = "1.3.1"

[build-dependencies]
tonic-build = "0.4.0"
