[package]
name = "etcd-proto"
version = "0.1.0"
authors = ["Andrew Jeffery <dev@jeffas.io>"]
edition = "2018"

[dependencies]
tonic = "0.4.0"
prost = "0.7.0"
serde = { version = "1.0.123", features = ["derive"] }

[build-dependencies]
tonic-build = "0.4.0"
